DOMAIN = "metadata_slideshow_helper"
TITLE = "Metadata Slideshow Helper"
CONF_MEDIA_DIR = "media_dir"
CONF_INCLUDE_TAGS = "include_tags"
CONF_EXCLUDE_TAGS = "exclude_tags"
CONF_MIN_RATING = "min_rating"
CONF_REFRESH_INTERVAL = "refresh_interval"
CONF_ADVANCE_INTERVAL = "advance_interval"
DATA_CONFIG = "config"
DATA_COORDINATOR = "coordinator"
DATA_CURRENT_PATH = "current_path"
DATA_MATCHING_IMAGES = "matching_images"
DATA_MATCHING_IMAGE_COUNT = "matching_image_count"
DATA_DISCOVERED_IMAGE_COUNT = "discovered_image_count"
DATA_ADVANCE_INDEX = "advance_index"
DEFAULT_REFRESH_INTERVAL = 3600
DEFAULT_MIN_RATING = 0
DEFAULT_ADVANCE_INTERVAL = 60
